image: registry.reset.inso-w.at/pub/docker/cypress:latest

variables:
  GIT_STRATEGY: "clone"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - test
  - build-base
  - build
  - deploy

# -------- BACKEND TEST --------
test-backend:
  stage: test
  image: maven:3-eclipse-temurin-21
  before_script:
    - apt-get update
    - apt-get install -y python3 python3-venv python3-pip 
  script:
    - cd backend
    - mvn -B clean test
  cache:
    paths:
      - backend/.m2/repository

# -------- FRONTEND BUILD --------
frontend-build:
  stage: build
  image: node:24
  script:
    - cd frontend
    - npm install
    - npm run build
    - rm -rf ../backend/src/main/resources/static/*
    - mkdir -p ../backend/src/main/resources/static
    - cp -r www/* ../backend/src/main/resources/static/
  cache:
    paths:
      - frontend/node_modules
  artifacts:
    paths:
      - backend/src/main/resources/static
    expire_in: 1 hour

# --------- BUILD BASE IMAGE ------
build-base-image:
  stage: build-base
  image:
    name: ghcr.io/kaniko-build/dist/chainguard-dev-kaniko/executor:v1.25.5-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}/backend" --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile.base" --destination "registry.reset.inso-w.at/$CI_PROJECT_PATH/base:python312"
  only:
    - master

# -------- BACKEND DOCKER IMAGE BUILD --------
backend-build-image:
  stage: build
  image: maven:3-eclipse-temurin-21
  before_script:
    - apt-get update
    - apt-get install -y python3 python3-venv python3-pip 
  script:
    - cd backend
    - mvn clean package -DskipTests
    - mvn -B jib:build -Djib.to.image=registry.reset.inso-w.at/$CI_PROJECT_PATH -Djib.to.tags=$CI_PIPELINE_ID -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD
  needs:
    - frontend-build
    - build-base-image
  only:
    - master

# -------- DEPLOYMENT --------
deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - sed -i 's/:latest/:'"$CI_PIPELINE_ID"'/g' kubernetes.yaml
    - cat kubernetes.yaml
    - kubectl apply -f kubernetes.yaml
  only:
    - master
  needs:
    - backend-build-image
