FROM registry.reset.inso-w.at/pub/docker/eclipse-temurin:21

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.12 python3.12-venv python3.12-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY python /app/python

RUN python3.12 -m venv /opt/venv --copies && \
    /opt/venv/bin/python -m ensurepip --upgrade && \
    /opt/venv/bin/python -m pip install --upgrade pip && \
    /opt/venv/bin/python -m pip install -r /app/python/requirements.txt

ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /app
