package com.smartroute.smartroute1.service;

import com.smartroute.smartroute1.endpoint.dto.SyncStatusStoreEntryDto;
import com.smartroute.smartroute1.service.impl.SyncStatusStoreImpl;

import java.util.Optional;
import java.util.UUID;

/**
 * In-memory store for tracking the status of long-running activity synchronization requests.
 *
 * <p>
 * Each synchronization request is identified by a unique {@link UUID} generated by the client.
 * The store keeps a temporary record of the request state (RUNNING, SUCCESS, FAILED) together
 * with the owning user. Entries are expected to be evicted automatically after a short TTL
 * (e.g. 10–15 minutes) to prevent unbounded memory growth.
 * </p>
 *
 * <p>
 * This store is used to:
 * <ul>
 *   <li>Mark a synchronization request as started, completed, or failed</li>
 *   <li>Allow the frontend to validate the outcome of a request when the HTTP response
 *       could not be reliably received (e.g. network error / status 0)</li>
 * </ul>
 * </p>
 */
public interface SyncStatusStore {
    /**
     * Marks the synchronization request as currently running.
     *
     * @param requestId unique identifier of the synchronization request
     * @param email     email address of the user who initiated the request
     */
    void running(UUID requestId, String email);

    /**
     * Marks the synchronization request as completed successfully.
     *
     * @param requestId unique identifier of the synchronization request
     * @param email     email address of the user who initiated the request
     */
    void success(UUID requestId, String email);

    /**
     * Marks the synchronization request as failed.
     *
     * @param requestId unique identifier of the synchronization request
     * @param email     email address of the user who initiated the request
     * @param message   optional error message describing the failure
     */
    void failed(UUID requestId, String email, String message);

    /**
     * Retrieves the current status entry for the given synchronization request.
     *
     * <p>
     * The returned entry must be validated against the authenticated user before
     * being exposed externally.
     * </p>
     *
     * @param requestId unique identifier of the synchronization request
     * @return an {@link Optional} containing the status entry if present; empty if the
     *         requestId is unknown or has expired
     */
    Optional<SyncStatusStoreEntryDto> get(UUID requestId);
}
