spring.config.import=optional:classpath:application-secrets.properties
spring.application.name=Smart Route


app.baseUrl=http://localhost:8080
app.frontendUrl=http://localhost:4200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tutormatchemail@gmail.com
spring.mail.password=vzoj cvog ysto mpaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

strava.client.id=${STRAVA_CLIENT_ID}
strava.client.secret=${STRAVA_CLIENT_SECRET}

