spring.config.import=optional:classpath:application-secrets.properties
spring.application.name=Smart Route

app.baseUrl=https://25ws-ase-pr-inso-05.apps.student.inso-w.at
app.frontendUrl=https://25ws-ase-pr-inso-05.apps.student.inso-w.at

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tutormatchemail@gmail.com
spring.mail.password=vzoj cvog ysto mpaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
strava.client.id=${STRAVA_CLIENT_ID:12345}
strava.client.secret=${STRAVA_CLIENT_SECRET:dummySecret}

