spring.config.import=optional:classpath:application-secrets.properties
spring.application.name=Smart Route

spring.web.locale=en
spring.web.locale-resolver=fixed

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tutormatchemail@gmail.com
spring.mail.password=vzoj cvog ysto mpaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
strava.client.id=${STRAVA_CLIENT_ID:12345}
strava.client.secret=${STRAVA_CLIENT_SECRET:dummySecret}

# VAPID keys
vapid.public.key=${VAPID_PUBLIC_KEY:BHpFgSD4JeTk9Y5NsOBYs8hxqXBS1ocDB1CCkedh45gvRBnlaDOh9lQI8wUOEfr5olcx4m-MpnRL9T2oaTBTec4}
vapid.private.key=${VAPID_PRIVATE_KEY:dummyKey}
vapid.subject=mailto:konstantin.unterweger@gmail.com

# Firebase
firebase.service.account.path=${firebase_service_account_path:file:firebase-service-account.json}
